# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

trigger:
  branches:
    include:
      - refs/tags/*
      - master

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test ./test/VioletGrass.Middleware.Test/VioletGrass.Middleware.Test.csproj --configuration $(buildConfiguration) --logger trx
    dotnet pack src/VioletGrass.Middleware/VioletGrass.Middleware.csproj --no-build --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    dotnet pack src/VioletGrass.Middleware.Experiments.StringRouter/VioletGrass.Middleware.Experiments.StringRouter.csproj --no-build --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: 'dotnet build & dotnet test'

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1